### ISSUE TITLE
only one of us knows how to set up IntelliJ

### ISSUE THREAD

**Issue by TomW1605** [QuickRecon/ScotchOARKit#14]
there is only one (to my knowledge) person in the group that knows how to setup IntelliJ. could u please provide instructions or a link?

**Comment by QuickRecon** [comment]
Will add to wiki when I can.

**Comment by Whoa-exclamation-mark** [comment]
It is a bit of a complicated process and if you need help ask me on Monday. Firstly download Java 8 and Python **2.7**. Once you have done this open IDEA and check out from version control - GitHub.

It will then open up and it will ask for maven auto import. Click Enable Auto-Import. It will ask you to download the python module and click yes

Then go to the top right and click the button with a file and a stairs of blue squares (project settings). In project SDK click new and add JDK 8. Then click modules on the left and go to OARKit. Delete under source folders Java\src\com (this will break every thing!). After this go under python and make sure that under dependencies Module SDK is correct (new, ect...). 

After this go up to the top and next to the play button click the down arrow. Then edit config. Press the add button at the top then maven. In the "command line" type clean generate-resources compile package. Then click add again then Application. In here make working directory to ./Java and then click the three dots on main class. Click Main then specify the module Java under Classpath of module. Do the same thing again but now under program arguments add server. Name your start configs at the top with Name. After this run the *_maven build once *_and you are good to go :)

**Comment by Whoa-exclamation-mark** [comment]
I will put this on the Wiki with pictures

**Comment by Whoa-exclamation-mark** [comment]
Added Wiki
