### ISSUE TITLE
Using a private chat for develpers

### ISSUE THREAD

**Issue by Whoa-exclamation-mark** [QuickRecon/ScotchOARKit#16]
Hi all,

It came to my attention with issue #15 that we do need a private chat so we do not fill up the issues with developing issues and there would be quicker response time and much more pros. I would recommend to use [HipChat](https://www.atlassian.com/software/hipchat) because it is made for developers and small teams are free. Post your recommendations and we will set it up next robotics session.

**Comment by QuickRecon** [comment]
Done some research, looks good.

**Comment by QuickRecon** [comment]
will we be running our own server?

**Comment by Whoa-exclamation-mark** [comment]
No the online version (you don't have to pay where as the host your own assumes each person has a paid subscription)

**Comment by TomW1605** [comment]
from what i can tell if we host our own server we need to pay and funding is tight as it is. i don't see any problem with just using the online version

**Comment by QuickRecon** [comment]
online version it is

**Comment by Whoa-exclamation-mark** [comment]
Does any one else have any other recommendations (eg. Team speak, ect...)?

**Comment by QuickRecon** [comment]
discord is nice, it has multiple chanels so there can be individual chats for each feature/issue but it doesn't have the code optimased features like hipchat.

**Comment by TomW1605** [comment]
the only other ones i have used are Line, WeChat and IRC none of which are optimised of developers like HipChat and the first 2 don't work at school

**Comment by Whoa-exclamation-mark** [comment]
I have setup HipChat and the link is https://scotchcollege.hipchat.com. Signup with your school email address for auto approval or email me and I will add you. Please post any recommendations on the name of the group (currently Scotch College...)

**Comment by joakee** [comment]
Why the scotchcollege.hipchat.com? Why not scotchrobotics.hipchat.com

**Comment by TomW1605** [comment]
we do have the problem (or blessing) that hipchat doesn't work at school without a vpn.

**Comment by joakee** [comment]
Why is it blocked though?

**Comment by TomW1605** [comment]
i dont know but i can only connect with a vpn
