### ISSUE TITLE
Scalability of UI

### ISSUE THREAD

**Issue by QuickRecon** [QuickRecon/ScotchOARKit#17]
The ui needs to become more scalable

**Comment by joakee** [comment]
I believe James was working on this, but he seemed to just halt progress about 2 weeks ago.

**Comment by TomW1605** [comment]
i think that was because Aren got annoyed that he was changing his code

**Comment by QuickRecon** [comment]
LOOK AT ME, I MAKE THE UI NOW.

**Comment by joakee** [comment]
Relevant meme: http://imgur.com/WzKQNoi

**Comment by QuickRecon** [comment]
http://i2.kym-cdn.com/entries/icons/original/000/012/132/thatsthejoke.jpg

**Comment by joakee** [comment]
I know...

**Comment by TomW1605** [comment]
i think i have got this fixed and by "think" i mean "can one of u cheak it please?"

**Comment by QuickRecon** [comment]
looks good
