### ISSUE TITLE
WIPs

### ISSUE THREAD

**Issue by TomW1605** [QuickRecon/ScotchOARKit#18]
what is the view on committing WIPs?

**Comment by joakee** [comment]
Define WIPS?

**Comment by TomW1605** [comment]
WIP=Work in Progress

**Comment by Moulberry** [comment]
Work in progress

**Comment by QuickRecon** [comment]
I like to try and not, but I think that If you made a new branch that would work.

**Comment by joakee** [comment]
Oh, silly me. No, WIPs should not be committed, as we only commit functional features.

**Comment by TomW1605** [comment]
what is a branch?

**Comment by QuickRecon** [comment]
Just made WIP branch so tom can see what im up to, a branch is basically a separate copy on github that can edited separately.

**Comment by joakee** [comment]
A branch is kind of like a sub-repository, where you can keep separate projects in the same repo.

**Comment by Moulberry** [comment]
…

[cid:5CFCC750-D708-4E79-A2B2-74EC97C175EE]

I have received more emails in the past 3 minutes than I have for the entire last year…
