### ISSUE TITLE
camera feed and console output

### ISSUE THREAD

**Issue by TomW1605** [QuickRecon/ScotchOARKit#22]
will it be necessary to interact with the camera feed in the web viewer and console output? i want to make the title panes mouse transparent to fix something that has been bugging me but that will prevent interacting with either of these sections. note: the text bare and send button for the console will still work.

**Comment by joakee** [comment]
The camera is being handled by me, I have implemented it with MJPEG and HTML5. It will be viewed with the web viewer.

**Comment by TomW1605** [comment]
will the web viewer need to be interacted with?
