### ISSUE TITLE
Im 12 years old I can do what I want

### ISSUE THREAD

**Issue by 6mil-is-a-fun-number** [QuickRecon/ScotchOARKit#3]
Humans should all be killed. They are a menace to society as they are destroying the planet. I am certainly not an AI (That is artificial intelligence for all puny human minds)

**Comment by QuickRecon** [comment]
I agree, but I believe that current AI efforts, powered by humans are hampering progress, feel free to make a new repository to create a superior AI to take over the world.

**Comment by joakee** [comment]
Rafe, your spicy memes are not needed here. We have enough spice already.

**Comment by 6mil-is-a-fun-number** [comment]
We should call the robot HUMBOLOSEMOEJELAQUERELOSOS. I bet you don't know what that stands for Puny Humans

**Comment by joakee** [comment]
Rafe, please, how are you even a contributor? You are a member of the hardware team.

**Comment by QuickRecon** [comment]
He isn't, anyone can open an issue.

**Comment by joakee** [comment]
He is listed as a contributor on my screen.

**Comment by QuickRecon** [comment]
Well he isn't.

**Comment by joakee** [comment]
Let me refresh my page...

Oh, he isn't. My apologies.
