### ISSUE TITLE
i think i changed somthing

### ISSUE THREAD

**Issue by TomW1605** [QuickRecon/ScotchOARKit#7]
i swear this was an acsedent and am hoping one of you can fix it or that it is not a problem
![screen shot 2016-03-17 at 8 41 13 pm 1](https://cloud.githubusercontent.com/assets/17092573/13846253/aaf2e730-ec80-11e5-8f83-ee9e69012dcc.png)

**Comment by QuickRecon** [comment]
Nah m8, just your project file, just checked the changes and nothing seems broken.
